package com.davidblackcn.buildupmobtweaks.feature;

import com.davidblackcn.buildupmobtweaks.BuildupMobTweaks;
import net.minecraft.resources.Identifier;

public enum FeatureId {
    PILLAGER_TARGET_LIFECYCLE("pillager_target_lifecycle"),
    PILLAGER_SPAWN_SUPPLIES("pillager_spawn_supplies"),
    SKELETON_AIM_FIX("skeleton_aim_fix"),
    GOLEM_FRIENDLY_FIRE_FIX("golem_friendly_fire_fix"),
    ZOMBIFIED_PIGLIN_ANGER_FIX("zombified_piglin_anger_fix"),
    STRAFE_HAZARD_CHECK("strafe_hazard_check"),
    MOVEMENT_JUMP_INPUT("movement_jump_input"),
    MOVEMENT_CLEAR_STRAFE("movement_clear_strafe"),
    STRAFE_OBSTACLE_JUMP("strafe_obstacle_jump"),
    PIGLIN_SHOT_SWING("piglin_shot_swing"),
    PIGLIN_ITEM_DODGE("piglin_item_dodge"),
    SKELETON_OFFHAND_VISUAL("skeleton_offhand_visual"),
    DROWNED_SWIM_VISUAL("drowned_swim_visual"),
    BURNING_PROJECTILE_VISUAL("burning_projectile_visual"),
    BURN_FREEZE_VISUAL("burn_freeze_visual"),
    UNDEAD_HORSE_SUNBURN("undead_horse_sunburn"),
    HOSTILE_ESCAPE_SEAT("hostile_escape_seat"),
    HOSTILE_SPAWN_EFFECT("hostile_spawn_effect"),
    SPIDER_HUNTS_PESTS("spider_hunts_pests"),
    CREEPER_FIRE_VISUAL("creeper_fire_visual"),
    CREEPER_HIT_DELAY("creeper_hit_delay"),
    CREEPER_EMBEDDED_ARROWS("creeper_embedded_arrows"),
    ILLUSIONER_OMEN_SPAWN("illusioner_omen_spawn"),
    ILLAGER_ZOMBIE_CONFLICT("illager_zombie_conflict"),
    ILLAGER_ZOMBIE_VILLAGER("illager_zombie_villager"),
    ILLAGER_BOATS("illager_boats"),
    HUSK_SPEAR_CHARGE("husk_spear_charge"),
    HUSK_CAMEL_CIRCLE("husk_camel_circle"),
    SKELETON_HORSE_CHARGE("skeleton_horse_charge"),
    CHICKEN_JOCKEY_CHARGE("chicken_jockey_charge"),
    ZOMBIE_SLIME_CARRIER("zombie_slime_carrier"),
    ZOMBIE_HORSE_LEADER("zombie_horse_leader"),
    PIGLIN_CROSSBOW_COMPATIBILITY("piglin_crossbow_compatibility"),
    PILLAGER_FOOD_HEAL("pillager_food_heal"),
    PILLAGER_SHIELD_BREAK("pillager_shield_break"),
    DROWNED_FISHING_PULL("drowned_fishing_pull"),
    ZOMBIFIED_PIGLIN_SPAWN_CROSSBOW("zombified_piglin_spawn_crossbow"),
    ZOMBIFIED_PIGLIN_CROSSBOW("zombified_piglin_crossbow"),
    ZOMBIE_FISHERMAN_ROD("zombie_fisherman_rod"),
    ZOMBIE_CLERIC_POTIONS("zombie_cleric_potions"),
    ZOMBIE_FLETCHER_CROSSBOW("zombie_fletcher_crossbow"),
    RIDER_FRIENDLY_FIRE("rider_friendly_fire"),
    SKELETON_TRAP_VARIANTS("skeleton_trap_variants"),
    SKELETON_WITHER_CONVERSION("skeleton_wither_conversion"),
    WITHER_SKELETON_BOW("wither_skeleton_bow"),
    WITHER_SKELETON_HOMING("wither_skeleton_homing"),
    WITHER_SKELETON_SKULL("wither_skeleton_skull"),
    PARCHED_DODGE("parched_dodge"),
    BOGGED_OMEN_MUSHROOMS("bogged_omen_mushrooms"),
    STRAY_OMEN_SNOW("stray_omen_snow"),
    STRAY_SNOW_BARRAGE("stray_snow_barrage"),
    SKELETON_SHELTER("skeleton_shelter"),
    ILLUSIONER_SWAP("illusioner_swap"),
    ILLUSIONER_SHOOT_PAUSE("illusioner_shoot_pause"),
    ILLUSIONER_CLONE_ARROWS("illusioner_clone_arrows"),
    ENDERMAN_COMBO_ANIMATION("enderman_combo_animation"),
    ENDERMAN_COMBO("enderman_combo"),
    ENDERMAN_SPEED("enderman_speed"),
    EVOKER_FIREBALL_NO_FIRE("evoker_fireball_no_fire"),
    EVOKER_TOTEM("evoker_totem"),
    EVOKER_FIREBALL("evoker_fireball"),
    GHAST_SLOW_FIREBALL("ghast_slow_fireball"),
    GHAST_COOLDOWN("ghast_cooldown"),
    GHAST_TELEGRAPH("ghast_telegraph"),
    BLAZE_ORBIT("blaze_orbit"),
    BLAZE_DIFFICULTY_VOLLEY("blaze_difficulty_volley"),
    BLAZE_STRAFE("blaze_strafe"),
    VEX_PROJECTILE_WEAKNESS("vex_projectile_weakness"),
    PILLAGER_CROSSBOW_COMPATIBILITY("pillager_crossbow_compatibility"),
    PILLAGER_RANGE("pillager_range"),
    SENSE_GLOWING("sense_glowing"),
    SENSE_BLINDNESS("sense_blindness"),
    SENSE_DARKNESS("sense_darkness"),
    SENSE_NAUSEA("sense_nausea"),
    SENSE_INVISIBILITY("sense_invisibility"),
    SENSE_CRAWLING("sense_crawling"),
    SENSE_CROUCHING("sense_crouching"),
    MELEE_EFFECT_INTERVAL("melee_effect_interval"),
    MELEE_HIGH_TARGET_JUMP("melee_high_target_jump"),
    RANGED_REPOSITION("ranged_reposition"),
    OMEN_PRESSURE("omen_pressure"),
    SILVERFISH_BURROW("silverfish_burrow"),
    SILVERFISH_CALL_PAUSE("silverfish_call_pause"),
    SILVERFISH_CALL_PARTICLES("silverfish_call_particles"),
    SILVERFISH_SHOVEL_WEAKNESS("silverfish_shovel_weakness"),
    BREEZE_TAKEOFF_BURST("breeze_takeoff_burst"),
    BREEZE_LANDING_BURST("breeze_landing_burst"),
    EVOKER_FLEE_SPEED("evoker_flee_speed"),
    EVOKER_AVOID_TARGET_FIX("evoker_avoid_target_fix"),
    HOSTILE_REST("hostile_rest"),
    REST_SOUND_WAKE("rest_sound_wake"),
    WITCH_LEAPING_POTION("witch_leaping_potion"),
    WITCH_JUMP_THROW("witch_jump_throw"),
    DIAGNOSTIC_PROBE("diagnostic_probe"),
    TRAITS("traits"),
    VEX_FIXED_CHARGE("vex_fixed_charge"),
    VEX_RECOVERY_PAUSE("vex_recovery_pause"),
    VEX_CLOSE_RANGE_GUARD("vex_close_range_guard"),
    PILLAGER_RETREAT("pillager_retreat"),
    PILLAGER_WEAPON_SWITCH("pillager_weapon_switch"),
    VINDICATOR_SUPPORT("vindicator_support"),
    EVOKER_VEX_LIMIT("evoker_vex_limit"),
    EVOKER_SUMMON_COOLDOWN("evoker_summon_cooldown"),
    WITCH_WINDUP("witch_windup"),
    WITCH_THROW_COOLDOWN("witch_throw_cooldown"),
    ZOMBIE_SHIELD_USE("zombie_shield_use"),
    ZOMBIE_DOOR_GUARD("zombie_door_guard"),
    ZOMBIE_ACTIVE_GUARD("zombie_active_guard"),
    HUSK_SAND_BURROW("husk_sand_burrow"),
    ZOMBIE_BABY_RIDER("zombie_baby_rider"),
    DROWNED_TRIDENT_CONSERVATION("drowned_trident_conservation"),
    DROWNED_TRIDENT_RECOVERY("drowned_trident_recovery"),
    DROWNED_TRIDENT_PLAYER_PICKUP("drowned_trident_player_pickup"),
    SKELETON_SAFE_STRAFING("skeleton_safe_strafing"),
    SKELETON_TARGET_VALIDATION("skeleton_target_validation"),
    SKELETON_WEAPON_SWITCHING("skeleton_weapon_switching"),
    SKELETON_BOW_COMPATIBILITY("skeleton_bow_compatibility"),
    SKELETON_SNIPING("skeleton_sniping"),
    STRAY_JUMP_SHOT("stray_jump_shot"),
    BOGGED_SPORE_RETREAT("bogged_spore_retreat"),
    EQUIPMENT_ASSIGNMENT("equipment_assignment"),
    TRAIT_COMMON_MARKER("demo_common"),
    TRAIT_ADVANCED_MARKER("demo_advanced"),
    TRAIT_RARE_MARKER("demo_rare");

    private final Identifier id;

    FeatureId(String path) {
        this.id = BuildupMobTweaks.id(path);
    }

    public Identifier id() {
        return id;
    }
}
