package com.davidblackcn.buildupmobtweaks;
import com.davidblackcn.buildupmobtweaks.rebuild.raid.*;
import com.davidblackcn.buildupmobtweaks.rebuild.evoker.VexLedger;
import net.fabricmc.fabric.api.gametest.v1.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.core.BlockPos;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.monster.*;
import net.minecraft.world.entity.monster.illager.Evoker;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.projectile.hurtingprojectile.SmallFireball;
import net.minecraft.world.entity.projectile.throwableitemprojectile.ThrownSplashPotion;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.item.*;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.level.GameType;
import net.minecraft.nbt.CompoundTag;
import java.util.*;

/** All AI starts via the real server and native selectors. Trait/health fixtures are explicitly directed. */
public class RaidBehaviorTests {
    static final String ARENA=SkeletonBehaviorTests.ARENA;
    static <T extends Mob>T mob(GameTestHelper h,EntityType<T> type){if(type==EntityTypes.VEX)for(int x=0;x<28;x++)for(int z=0;z<28;z++)for(int y=-4;y<=0;y++)h.setBlock(new BlockPos(x,y,z),net.minecraft.world.level.block.Blocks.STONE);var m=type.create(h.getLevel(),EntitySpawnReason.COMMAND);m.snapTo(h.absolutePos(new BlockPos(8,2,8)),0,0);m.setPersistenceRequired();if(m instanceof Vex v)v.setBoundOrigin(m.blockPosition());h.getLevel().addFreshEntity(m);return m;}
    static SkeletonBehaviorTests.PlayerFixture player(GameTestHelper h){var f=SkeletonBehaviorTests.player(h);f.player().getAttribute(Attributes.MAX_HEALTH).setBaseValue(1000);f.player().setHealth(1000);f.player().snapTo(h.absolutePos(new BlockPos(8,2,17)),0,0);return f;}
    static Evoker evoker(GameTestHelper h,String birth){var m=mob(h,EntityTypes.EVOKER);m.getAttribute(Attributes.MOVEMENT_SPEED).setBaseValue(0);m.getAttached(RaidState.EVOKER).putString("birth",birth);return m;}
    static void proof(String scenario,Mob m,String detail){var r=RaidState.runtime(m);BuildupMobTweaks.LOGGER.info("R4C_EVIDENCE scenario={} uuid={} ticks={} previews={} throws={} leaps={} jumps={} casts={} releases={} totems={} charges={} {}",scenario,m.getUUID(),m.tickCount,r.previews,r.throwsMade,r.leaps,r.jumps,r.casts,r.releases,r.totems,r.charges,detail);}
    static void clean(Evoker m){for(var v:m.level().getEntitiesOfClass(Vex.class,m.getBoundingBox().inflate(70)))if(v.getOwnerReference()!=null&&v.getOwnerReference().matches(m))v.discard();m.discard();}

    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=350)
    public void witchActualPreviewProjectileAndWorldCooldown(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=mob(h,EntityTypes.WITCH);var f=player(h);
        Set<UUID> projectiles=new HashSet<>();List<Long> times=new ArrayList<>();boolean[] preview={false};long[] firstPreview={-1};
        h.onEachTick(()->{if(TemporaryItem.is(m.getMainHandItem(),"preview")){preview[0]=true;if(firstPreview[0]<0)firstPreview[0]=h.getLevel().getGameTime();}
            for(var p:h.getLevel().getEntitiesOfClass(ThrownSplashPotion.class,m.getBoundingBox().inflate(40),p->p.getOwner()==m))if(projectiles.add(p.getUUID()))times.add(h.getLevel().getGameTime());});
        h.runAtTickTime(330,()->{h.assertTrue(m.getTarget()==f.player()&&preview[0]&&times.size()>=2,"Native survival acquisition, real preview and two real projectiles");
            h.assertTrue(times.getFirst()-firstPreview[0]>=20,"Full default world-tick windup");for(int i=1;i<times.size();i++)h.assertTrue(times.get(i)-times.get(i-1)>=100,"Actual projectiles respect independent cooldown");
            proof("W01_default",m,"projectile_times="+times+" preview_start="+firstPreview[0]+" playerHealth="+f.player().getHealth());m.discard();f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=220)
    public void witchWindupOffActuallyThrowsVanillaPotion(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=mob(h,EntityTypes.WITCH);m.addTag("buildupmobtweaks:disable_witch_windup");var f=player(h);boolean[] seen={false};
        h.onEachTick(()->{if(!h.getLevel().getEntitiesOfClass(ThrownSplashPotion.class,m.getBoundingBox().inflate(30),p->p.getOwner()==m).isEmpty())seen[0]=true;});
        h.runAtTickTime(200,()->{h.assertTrue(seen[0]&&RaidState.runtime(m).previews==0,"Independent windup off retains actual native throw");proof("W01_windup_off",m,"projectile=true");m.discard();f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=220)
    public void witchPreviewCreativeExitAndExternalEquipmentSurvive(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=mob(h,EntityTypes.WITCH);var f=player(h);boolean[] triggered={false};
        h.onEachTick(()->{if(!triggered[0]&&RaidState.runtime(m).preview){triggered[0]=true;f.player().setGameMode(GameType.CREATIVE);}});
        h.runAtTickTime(180,()->{h.assertTrue(triggered[0]&&m.getTarget()==null&&!RaidState.runtime(m).preview&&m.getMainHandItem().isEmpty(),"Creative exit aborts preview without projectile or lost original item");
            var sword=new ItemStack(Items.DIAMOND_SWORD);m.setItemSlot(EquipmentSlot.MAINHAND,sword);m.addTag("buildupmobtweaks:vanilla_ai");h.runAfterDelay(10,()->{h.assertTrue(m.getMainHandItem()==sword,"Foreign main hand survives our cleanup");proof("W01_creative_exit",m,"external_preserved=true");m.discard();f.close();h.succeed();});});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=240)
    public void witchPreviewReloadKeepsCooldownAndDiscardsTemporaryItem(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);Witch[] refs={mob(h,EntityTypes.WITCH)};var f=player(h);boolean[] reloaded={false};
        h.onEachTick(()->{if(!reloaded[0]&&RaidState.runtime(refs[0]).preview){reloaded[0]=true;refs[0]=CombatTestWorld.reload(h,refs[0]);refs[0].addTag("buildupmobtweaks:vanilla_ai");}});
        h.runAtTickTime(200,()->{h.assertTrue(reloaded[0]&&!RaidState.runtime(refs[0]).preview&&!TemporaryItem.is(refs[0].getMainHandItem(),"preview"),"Actual save/load aborts in-flight preview");proof("W01_reload",refs[0],"temporary=false");refs[0].discard();f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=450)
    public void witchActuallyDrinksLeapingAndJumpsToThrow(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);for(int x=6;x<=10;x++)for(int z=15;z<=19;z++)h.setBlock(new BlockPos(x,4,z),net.minecraft.world.level.block.Blocks.STONE);
        var m=mob(h,EntityTypes.WITCH);var f=player(h);f.player().snapTo(h.absolutePos(new BlockPos(8,5,17)),0,0);boolean[] drinking={false},effect={false};double base=m.getY();double[] high={base};
        h.onEachTick(()->{if(m.isDrinkingPotion()&&TemporaryItem.is(m.getMainHandItem(),"leap"))drinking[0]=true;if(m.hasEffect(MobEffects.JUMP_BOOST))effect[0]=true;high[0]=Math.max(high[0],m.getY());});
        h.runAtTickTime(425,()->{h.assertTrue(drinking[0]&&effect[0],"Actual native drinking completes and applies jump boost");h.assertTrue(RaidState.runtime(m).jumps>0&&high[0]-base>.5&&RaidState.runtime(m).throwsMade>0,"Actual jump and projectile throw after native potion");proof("W02_high_target",m,"drink=true effect=true height="+(high[0]-base));m.discard();f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=380)
    public void evokerThreeRealOrbitEntitiesReleaseAndFiniteCooldown(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=evoker(h,"fireball");var f=player(h);int[] max={0};boolean[] moved={false};Map<UUID,net.minecraft.world.phys.Vec3> positions=new HashMap<>();
        h.onEachTick(()->{int bound=0;for(var b:h.getLevel().getEntitiesOfClass(SmallFireball.class,m.getBoundingBox().inflate(35),b->b.getOwner()==m)){if(b.isPassenger()){bound++;var prev=positions.put(b.getUUID(),b.position());if(prev!=null&&b.position().distanceTo(prev)>.02)moved[0]=true;}}max[0]=Math.max(max[0],bound);});
        h.runAtTickTime(350,()->{h.assertTrue(max[0]==3&&moved[0]&&RaidState.runtime(m).releases==3,"Three actual moving orbit passengers and three actual releases");h.assertTrue(!Boolean.TRUE.equals(m.getAttached(RaidState.ACTIVE))&&m.getAttached(RaidState.EVOKER).getLongOr("special_ready",0)>h.getLevel().getGameTime(),"Finite phase and persistent default cooldown");
            proof("E01_real_orbit",m,"max_passengers="+max[0]+" orbit_moved="+moved[0]);clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=230)
    public void evokerOrbitDisableCleansOnlyOwnedEntities(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=evoker(h,"fireball");var f=player(h);boolean[] changed={false};
        var outside=new ItemStack(Items.SHIELD);m.setItemSlot(EquipmentSlot.OFFHAND,outside);
        h.onEachTick(()->{if(!changed[0]&&!m.getPassengers().isEmpty()){changed[0]=true;m.addTag("buildupmobtweaks:disable_evoker_fireball");}});
        h.runAtTickTime(210,()->{h.assertTrue(changed[0]&&RaidState.runtime(m).balls.isEmpty()&&m.getPassengers().isEmpty()&&!Boolean.TRUE.equals(m.getAttached(RaidState.ACTIVE)),"Disable cancels actual orbit and bounded pose");h.assertTrue(m.getOffhandItem()==outside,"Foreign shield preserved");proof("E01_disable",m,"owned_balls=0 shield=true");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=230)
    public void evokerOrbitPassengerSaveLoadDoesNotDuplicate(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);Evoker[] refs={evoker(h,"fireball")};var f=player(h);boolean[] saved={false};long[] ready={0};
        h.onEachTick(()->{var m=refs[0];if(!saved[0]&&m.getPassengers().size()==2){saved[0]=true;ready[0]=m.getAttached(RaidState.EVOKER).getLongOr("special_ready",0);refs[0]=CombatTestWorld.reloadPassengers(h,m);}});
        h.runAtTickTime(210,()->{var m=refs[0];h.assertTrue(saved[0]&&m.getPassengers().isEmpty()&&h.getLevel().getEntitiesOfClass(SmallFireball.class,m.getBoundingBox().inflate(35),b->RaidState.known(b,RaidState.BALL)).isEmpty(),"Actual recursive save/load leaves no in-flight orbit or duplicates");h.assertTrue(m.getAttached(RaidState.EVOKER).getLongOr("special_ready",0)==ready[0],"World cooldown retained");proof("E01_reload",m,"duplicate_balls=0 ready="+ready[0]);clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=600)
    public void evokerRealTotemConsumedOnceAndNoExtraDeathLoot(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=evoker(h,"totem");m.setHealth(4);var f=player(h);boolean[] consumed={false};
        h.onEachTick(()->{if(!consumed[0]&&TemporaryItem.is(m.getOffhandItem(),"totem")){h.assertTrue(m.getHealth()<m.getMaxHealth()*.2f,"Actual threshold under 20 percent");m.hurtServer(h.getLevel(),m.damageSources().mobAttack(f.player()),100);consumed[0]=true;
            proof("E02_consume_probe",m,"alive="+m.isAlive()+" health="+m.getHealth()+" offhand="+m.getOffhandItem()+" regen="+m.hasEffect(MobEffects.REGENERATION));
            h.assertTrue(m.isAlive()&&m.getHealth()==1&&m.getOffhandItem().isEmpty()&&m.hasEffect(MobEffects.REGENERATION),"Native death protection consumes real totem and revives");}});
        h.runAtTickTime(530,()->{h.assertTrue(consumed[0]&&RaidState.runtime(m).totems==1&&m.getAttached(RaidState.EVOKER).getBooleanOr("totem_spent",false),"Lifetime once budget recorded");m.hurtServer(h.getLevel(),m.damageSources().mobAttack(f.player()),1000);});
        h.runAtTickTime(560,()->{int count=0;for(var item:h.getLevel().getEntitiesOfClass(ItemEntity.class,m.getBoundingBox().inflate(15)))if(item.getItem().is(Items.TOTEM_OF_UNDYING))count+=item.getItem().getCount();h.assertTrue(!m.isAlive()&&count==1,"Exactly one vanilla loot-table totem; no generated equipment bonus");proof("E02_native_consume_death",m,"loot_totems="+count);clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=240)
    public void evokerExistingOffhandNeverReplacedByClutch(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=evoker(h,"totem");m.setHealth(4);var original=new ItemStack(Items.SHIELD);m.setItemSlot(EquipmentSlot.OFFHAND,original);var f=player(h);
        h.runAtTickTime(210,()->{h.assertTrue(m.getOffhandItem()==original&&RaidState.runtime(m).totems==0&&!m.getAttached(RaidState.EVOKER).getBooleanOr("totem_spent",false),"Original offhand excludes generated clutch and remains intact");proof("E02_existing_offhand",m,"unchanged=true");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=250)
    public void evokerTotemWindowExpiresAndReloadKeepsSpent(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);Evoker[] refs={evoker(h,"totem")};refs[0].setHealth(4);var f=player(h);boolean[] loaded={false};
        h.onEachTick(()->{if(!loaded[0]&&TemporaryItem.is(refs[0].getOffhandItem(),"totem")){loaded[0]=true;refs[0]=CombatTestWorld.reload(h,refs[0]);}});
        h.runAtTickTime(225,()->{var m=refs[0];h.assertTrue(loaded[0]&&m.getOffhandItem().isEmpty()&&m.getAttached(RaidState.EVOKER).getBooleanOr("totem_spent",false)&&RaidState.runtime(m).totems==0,"Actual reload removes temporary totem and never regenerates lifetime window");proof("E02_reload",m,"spent=true");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=1000)
    public void evokerNativeSummonUsesLedgerAndDefaultCooldown(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=evoker(h,"none");var f=player(h);Set<UUID> seen=new HashSet<>();List<Long> batches=new ArrayList<>();int[] peak={0};
        h.onEachTick(()->{boolean fresh=false;for(var v:h.getLevel().getEntitiesOfClass(Vex.class,m.getBoundingBox().inflate(70),v->v.getOwnerReference()!=null&&v.getOwnerReference().matches(m)))if(seen.add(v.getUUID()))fresh=true;if(fresh)batches.add(h.getLevel().getGameTime());peak[0]=Math.max(peak[0],VexLedger.count(m));});
        h.runAtTickTime(300,()->{h.assertTrue(seen.size()==3&&VexLedger.count(m)==3,"Normal difficulty native summon spawned and indexed exactly three");});
        h.runAtTickTime(950,()->{h.assertTrue(batches.size()>=2&&peak[0]<=6,"Actual second native summon without exceeding owner budget");h.assertTrue(batches.get(1)-batches.get(0)>=680,"Default world-time summon interval");proof("E03_native_schedule",m,"batches="+batches+" peak="+peak[0]+" spawned="+seen.size());clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=230)
    public void evokerFullOwnerBudgetBlocksNativeSummon(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=evoker(h,"none");var f=player(h);List<Vex> reserved=new ArrayList<>();
        for(int i=0;i<6;i++){var v=EntityTypes.VEX.create(h.getLevel(),EntitySpawnReason.COMMAND);v.setOwner(m);v.setNoAi(true);v.snapTo(m.position().add(25,2,i),0,0);h.getLevel().addFreshEntity(v);reserved.add(v);}
        h.runAtTickTime(200,()->{h.assertTrue(VexLedger.count(m)==6,"Real owned entities fill ledger without nearby vanilla-count interference");h.assertTrue(m.getAttached(RaidState.EVOKER).getLongOr("summon_ready",0)==0,"Full owner budget rejects native summon start");reserved.getFirst().discard();h.runAfterDelay(5,()->{h.assertTrue(VexLedger.count(m)==5,"Actual destruction releases one owner slot");proof("E03_full_budget",m,"count=5 released=1");reserved.forEach(Entity::discard);clean(m);f.close();h.succeed();});});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=440)
    public void vexFixedChargeUsesSnapshotAndNativeHit(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=mob(h,EntityTypes.VEX);m.setItemSlot(EquipmentSlot.MAINHAND,new ItemStack(Items.IRON_SWORD));var f=player(h);boolean[] hit={false};long[] start={-1};net.minecraft.world.phys.Vec3[] dir={null},pos={null};double[] error={0};
        h.onEachTick(()->{var r=RaidState.runtime(m);if(r.charging){if(start[0]<0){start[0]=h.getLevel().getGameTime();dir[0]=r.direction;pos[0]=m.position();}else if(h.getLevel().getGameTime()-start[0]<3){var delta=m.position().subtract(pos[0]);if(delta.length()>.2)error[0]=Math.max(error[0],1-delta.normalize().dot(dir[0]));}}if(f.player().getHealth()<1000)hit[0]=true;});
        h.runAtTickTime(410,()->{proof("V01_hit_probe",m,"start="+start[0]+" hit="+hit[0]+" target="+m.getTarget());h.assertTrue(start[0]>=0&&RaidState.runtime(m).charges>0&&hit[0],"Real native charge starts and native collision deals actual melee damage");h.assertTrue(error[0]<.02,"Actual motion follows snapshot direction");proof("V01_native_hit",m,"playerHealth="+f.player().getHealth()+" direction_error="+error[0]);m.discard();f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=460)
    public void vexMovingTargetCannotBendChargeAndRecoveryPauses(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=mob(h,EntityTypes.VEX);m.getRandom().setSeed(440301);var f=player(h);boolean[] moved={false},ended={false};net.minecraft.world.phys.Vec3[] dir={null},end={null};long[] ready={0};double[] error={0},pause={0};
        h.onEachTick(()->{var r=RaidState.runtime(m);if(r.charging&&!moved[0]){moved[0]=true;dir[0]=r.direction;f.player().snapTo(f.player().position().add(8,0,0),0,0);}
            if(moved[0]&&!ended[0]&&r.charging){error[0]=Math.max(error[0],1-r.direction.dot(dir[0]));}
            if(moved[0]&&!r.charging&&!ended[0]){ended[0]=true;ready[0]=m.getAttached(RaidState.VEX).getLongOr("charge_ready",0);end[0]=m.position();}
            if(ended[0]&&h.getLevel().getGameTime()<ready[0])pause[0]=Math.max(pause[0],m.position().distanceTo(end[0]));});
        h.runAtTickTime(430,()->{proof("V01_recovery_probe",m,"moved="+moved[0]+" ended="+ended[0]+" error="+error[0]+" ready="+ready[0]+" pause="+pause[0]);h.assertTrue(moved[0]&&ended[0]&&error[0]<.00001&&ready[0]>0,"Target movement cannot retarget fixed phase; phase terminates with recovery budget");h.assertTrue(pause[0]<.15,"Actual recovery world ticks stop movement");proof("V01_snapshot_recovery",m,"direction_error="+error[0]+" pause_motion="+pause[0]);m.discard();f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=430)
    public void vexCloseGuardAndIndependentFixedOffUseNativeFallback(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=mob(h,EntityTypes.VEX);var f=player(h);f.player().snapTo(m.position().add(0,0,2.5),0,0);m.setNoGravity(true);
        h.runAtTickTime(30,()->{h.assertTrue(RaidState.runtime(m).charges==0,"Default close-range guard refuses directed 2.5 block start");m.addTag("buildupmobtweaks:disable_vex_fixed_charge");m.addTag("buildupmobtweaks:disable_vex_close_range_guard");f.player().snapTo(m.position().add(0,0,8),0,0);});
        boolean[] nativeCharge={false};h.onEachTick(()->{if(m.isCharging()&&!RaidState.runtime(m).charging)nativeCharge[0]=true;});
        h.runAtTickTime(400,()->{proof("V01_fallback_probe",m,"target="+m.getTarget()+" hasWanted="+m.getMoveControl().hasWanted());h.assertTrue(nativeCharge[0]&&RaidState.runtime(m).charges==0,"Independent fixed off resumes real native charge");proof("V01_native_fallback",m,"native_charge=true");m.discard();f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=430)
    public void vexActiveCreativeAndReloadAbortDirection(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);Vex[] refs={mob(h,EntityTypes.VEX)};var f=player(h);boolean[] changed={false};
        h.onEachTick(()->{if(!changed[0]&&RaidState.runtime(refs[0]).charging){changed[0]=true;refs[0]=CombatTestWorld.reload(h,refs[0]);f.player().setGameMode(GameType.SPECTATOR);}});
        h.runAtTickTime(400,()->{proof("V01_reload_probe",refs[0],"changed="+changed[0]+" target="+refs[0].getTarget()+" charging="+refs[0].isCharging());h.assertTrue(changed[0]&&refs[0].getTarget()==null&&!refs[0].isCharging()&&!RaidState.runtime(refs[0]).charging,"Actual reload plus spectator exit removes in-flight charge");proof("V01_reload_spectator",refs[0],"charging=false");refs[0].discard();f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=60)
    public void futureAttachmentVersionLeavesAllNativeGoalsUntouched(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var e=EntityTypes.EVOKER.create(h.getLevel(),EntitySpawnReason.LOAD);var d=new CompoundTag();d.putInt("version",99);d.putString("sentinel","untouched");e.setAttached(RaidState.EVOKER,d);e.snapTo(h.absolutePos(new BlockPos(8,2,8)),0,0);h.getLevel().addFreshEntity(e);
        h.runAtTickTime(35,()->{h.assertTrue(e.getAttached(RaidState.EVOKER).equals(d)&&e.getGoalSelector().getAvailableGoals().stream().noneMatch(g->g.getGoal().getClass().getName().startsWith("com.davidblackcn.buildupmobtweaks.rebuild.evoker")),"Unknown persistent version preserved without installing new goals");proof("future_data",e,"version=99 untouched=true");e.discard();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=65)
    public void actualProjectileImpactNoFireGatePreservesNativeDamage(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=evoker(h,"fireball");m.setNoAi(true);var t=SkeletonBehaviorTests.target(h,8,15);var b=new SmallFireball(h.getLevel(),m,new net.minecraft.world.phys.Vec3(0,0,1));var d=new CompoundTag();d.putInt("version",1);d.putLong("expires",h.getLevel().getGameTime()+200);b.setAttached(RaidState.BALL,d);b.snapTo(m.position().add(0,1,2),0,0);h.getLevel().addFreshEntity(b);
        h.runAtTickTime(40,()->{h.assertTrue(b.isRemoved()&&t.getHealth()<100&&!t.isOnFire(),"Real native projectile collision damages, discards and independent no-fire prevents ignition");proof("E01_native_impact_no_fire",m,"targetHealth="+t.getHealth()+" fire="+t.isOnFire());clean(m);t.discard();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=65)
    public void actualProjectileImpactFireGateOffUsesNativeIgnition(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=evoker(h,"fireball");m.setNoAi(true);m.addTag("buildupmobtweaks:disable_evoker_fireball_no_fire");var t=SkeletonBehaviorTests.target(h,8,15);var b=new SmallFireball(h.getLevel(),m,new net.minecraft.world.phys.Vec3(0,0,1));var d=new CompoundTag();d.putInt("version",1);d.putLong("expires",h.getLevel().getGameTime()+200);b.setAttached(RaidState.BALL,d);b.snapTo(m.position().add(0,1,2),0,0);h.getLevel().addFreshEntity(b);
        h.runAtTickTime(40,()->{h.assertTrue(b.isRemoved()&&t.getHealth()<100&&t.isOnFire(),"Independent no-fire off restores actual native ignition and damage");proof("E01_native_impact_fire",m,"targetHealth="+t.getHealth()+" fire="+t.isOnFire());clean(m);t.discard();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=280)
    public void evokerFortyWorldTickWindowExpiresWithoutResurrection(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=evoker(h,"totem");m.setHealth(4);var f=player(h);long[] first={-1},last={-1};
        h.onEachTick(()->{if(TemporaryItem.is(m.getOffhandItem(),"totem")){if(first[0]<0)first[0]=h.getLevel().getGameTime();last[0]=h.getLevel().getGameTime();}});
        h.runAtTickTime(255,()->{h.assertTrue(first[0]>=0&&last[0]-first[0]>=39&&last[0]-first[0]<=41&&m.getOffhandItem().isEmpty()&&RaidState.runtime(m).totems==1,"Actual finite 40 world tick window expires, lifetime budget remains spent");proof("E02_window_expiry",m,"first="+first[0]+" last="+last[0]);clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=260)
    public void evokerTotemDisablePreservesExternalReplacementAndSpentBudget(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=evoker(h,"totem");m.setHealth(4);var f=player(h);var sword=new ItemStack(Items.DIAMOND_SWORD);boolean[] changed={false};
        h.onEachTick(()->{if(!changed[0]&&TemporaryItem.is(m.getOffhandItem(),"totem")){changed[0]=true;m.setItemSlot(EquipmentSlot.OFFHAND,sword);m.addTag("buildupmobtweaks:disable_evoker_totem");}});
        h.runAtTickTime(230,()->{h.assertTrue(changed[0]&&m.getOffhandItem()==sword&&!Boolean.TRUE.equals(m.getAttached(RaidState.ACTIVE))&&m.getAttached(RaidState.EVOKER).getBooleanOr("totem_spent",false),"Disable aborts window without deleting foreign replacement or refunding budget");proof("E02_disable_replacement",m,"external=true spent=true");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=260)
    public void evokerFireTraitDisabledActuallyKeepsNativeSummoning(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=evoker(h,"fireball");m.addTag("buildupmobtweaks:disable_evoker_fireball");var f=player(h);
        h.runAtTickTime(230,()->{h.assertTrue(RaidState.runtime(m).casts==0&&VexLedger.count(m)==3,"Fireball off retains actual native summon instead of disabling all combat");proof("E01_native_fallback",m,"vex="+VexLedger.count(m));clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=260)
    public void witchLeapingAndJumpGatesOffKeepActualVanillaThrow(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=mob(h,EntityTypes.WITCH);m.addTag("buildupmobtweaks:disable_witch_leaping_potion");m.addTag("buildupmobtweaks:disable_witch_jump_throw");var f=player(h);
        h.runAtTickTime(230,()->{h.assertTrue(RaidState.runtime(m).throwsMade>0&&RaidState.runtime(m).leaps==0&&RaidState.runtime(m).jumps==0,"Independent W02 off retains actual W01 throwing");proof("W02_gates_off",m,"throw=true leap=0 jump=0");m.discard();f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=65)
    public void actualFinalizeSpawnSamplesExclusiveDefaultTraitsWithoutReroll(GameTestHelper h){int fire=0,totem=0;for(int i=0;i<1000;i++){var m=EntityTypes.EVOKER.create(h.getLevel(),EntitySpawnReason.NATURAL);m.finalizeSpawn(h.getLevel(),h.getLevel().getCurrentDifficultyAt(h.absolutePos(BlockPos.ZERO)),EntitySpawnReason.NATURAL,null);String birth=m.getAttached(RaidState.EVOKER).getStringOr("birth","missing");if(birth.equals("fireball"))fire++;else if(birth.equals("totem"))totem++;else h.assertTrue(birth.equals("none"),"Only known exclusive outcomes");var copy=m.getAttached(RaidState.EVOKER).copy();m.finalizeSpawn(h.getLevel(),h.getLevel().getCurrentDifficultyAt(h.absolutePos(BlockPos.ZERO)),EntitySpawnReason.SPAWN_ITEM_USE,null);h.assertTrue(copy.equals(m.getAttached(RaidState.EVOKER)),"Repeated native finalizeSpawn does not reroll");m.discard();}
        h.assertTrue(fire>30&&fire<120&&totem>0&&totem<35,"Default weighted fixture sample is consistent with 70/10 per thousand");BuildupMobTweaks.LOGGER.info("R4C_EVIDENCE scenario=E01_E02_default_birth n=1000 fireball={} totem={} native_finalizeSpawn=true natural_spawner=NOT_RUN",fire,totem);h.succeed();}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=280)
    public void witchNativeRaidAllyHealingBypassesHostilePreviewAndCooldown(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=mob(h,EntityTypes.WITCH);var ally=EntityTypes.PILLAGER.create(h.getLevel(),EntitySpawnReason.COMMAND);ally.snapTo(h.absolutePos(new BlockPos(8,2,15)),0,0);ally.setNoAi(true);ally.setHealth(3);ally.addTag("buildupmobtweaks:vanilla_ai");h.getLevel().addFreshEntity(ally);
        // Directed native active-Raid membership, not a complete village raid or a direct Goal call.
        var raid=new net.minecraft.world.entity.raid.Raid(m.blockPosition(),h.getLevel().getDifficulty());m.setCurrentRaid(raid);ally.setCurrentRaid(raid);m.getAttached(RaidState.WITCH).putLong("throw_ready",h.getLevel().getGameTime()+10000);
        boolean[] healed={false};h.onEachTick(()->{if(ally.getHealth()>3)healed[0]=true;});
        h.runAtTickTime(250,()->{h.assertTrue(healed[0]&&RaidState.runtime(m).throwsMade>0&&RaidState.runtime(m).previews==0,"Native heal-raider selector, actual potion and ally healing bypass hostile cooldown and preview");proof("W01_limited_raid_heal",m,"allyHealth="+ally.getHealth()+" full_raid=NOT_RUN");m.setCurrentRaid(null);ally.setCurrentRaid(null);raid.stop();m.discard();ally.discard();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=270)
    public void evokerCreativeDuringOrbitReleasesTargetAndAllOwnedBalls(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=evoker(h,"fireball");var f=player(h);boolean[] changed={false};
        h.onEachTick(()->{if(!changed[0]&&!m.getPassengers().isEmpty()){changed[0]=true;f.player().setGameMode(GameType.CREATIVE);}});
        h.runAtTickTime(240,()->{h.assertTrue(changed[0]&&m.getTarget()==null&&m.getPassengers().isEmpty()&&RaidState.runtime(m).balls.isEmpty()&&!Boolean.TRUE.equals(m.getAttached(RaidState.ACTIVE)),"Actual creative transition exits target, orbit, owned projectiles and pose");proof("E01_creative_exit",m,"balls=0 target=none");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=270)
    public void evokerNoAiDuringOrbitAndDeathLeaveNoOwnEntities(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=evoker(h,"fireball");var f=player(h);boolean[] changed={false};
        h.onEachTick(()->{if(!changed[0]&&!m.getPassengers().isEmpty()){changed[0]=true;m.setNoAi(true);}});
        h.runAtTickTime(230,()->{h.assertTrue(changed[0]&&m.getPassengers().isEmpty()&&RaidState.runtime(m).balls.isEmpty()&&!Boolean.TRUE.equals(m.getAttached(RaidState.ACTIVE)),"NoAI aborts in-flight orbit during actual entity tick without selector updates");m.hurtServer(h.getLevel(),m.damageSources().generic(),1000);});
        h.runAtTickTime(255,()->{h.assertTrue(!m.isAlive()&&h.getLevel().getEntitiesOfClass(SmallFireball.class,m.getBoundingBox().inflate(40),b->b.getOwner()==m).isEmpty(),"Actual death leaves zero own projectiles");proof("E01_noai_death",m,"balls=0");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4c",structure=ARENA,maxTicks=105)
    public void actualBlockImpactNoFireThenIndependentGateRestoresFire(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);for(int x=6;x<=10;x++)for(int y=2;y<=4;y++)h.setBlock(new BlockPos(x,y,14),net.minecraft.world.level.block.Blocks.STONE);var m=evoker(h,"fireball");m.setNoAi(true);
        java.util.function.Supplier<SmallFireball> launch=()->{var b=new SmallFireball(h.getLevel(),m,new net.minecraft.world.phys.Vec3(0,0,1));var d=new CompoundTag();d.putInt("version",1);d.putLong("expires",h.getLevel().getGameTime()+200);b.setAttached(RaidState.BALL,d);b.snapTo(m.position().add(0,.3,2),0,0);h.getLevel().addFreshEntity(b);return b;};var first=launch.get();SmallFireball[] second={null};
        h.runAtTickTime(35,()->{h.assertTrue(first.isRemoved()&&h.getLevel().getBlockState(h.absolutePos(new BlockPos(8,2,13))).isAir(),"Actual block collision discarded first own fireball without placing fire");m.addTag("buildupmobtweaks:disable_evoker_fireball_no_fire");second[0]=launch.get();});
        h.runAtTickTime(80,()->{h.assertTrue(second[0].isRemoved()&&h.getLevel().getBlockState(h.absolutePos(new BlockPos(8,2,13))).is(net.minecraft.world.level.block.Blocks.FIRE),"Independent no-fire off restores actual native terrain ignition under mobGriefing");proof("E01_block_impact",m,"no_fire_then_native_fire=true");clean(m);h.succeed();});}
}
