package com.davidblackcn.buildupmobtweaks;
import com.davidblackcn.buildupmobtweaks.rebuild.remaining.*;
import net.fabricmc.fabric.api.gametest.v1.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.monster.*;
import net.minecraft.world.entity.monster.breeze.Breeze;
import net.minecraft.world.entity.monster.spider.Spider;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.projectile.hurtingprojectile.*;
import net.minecraft.world.entity.projectile.arrow.AbstractArrow;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.item.*;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.core.BlockPos;
import java.util.*;
/** Fixtures supply combat inputs; only actual Server Tick and native Goal/Brain schedules run AI. */
public class RemainingBehaviorTests {
    static final String ARENA=SkeletonBehaviorTests.ARENA;
    static <T extends Mob>T mob(GameTestHelper h,EntityType<T> type){SkeletonBehaviorTests.floor(h,false);if(type==EntityTypes.SILVERFISH)for(int x=0;x<28;x++)for(int z=0;z<28;z++)h.setBlock(new BlockPos(x,1,z),Blocks.OBSIDIAN);var m=type.create(h.getLevel(),EntitySpawnReason.COMMAND);m.snapTo(h.absolutePos(new BlockPos(8,2,8)),0,0);m.setPersistenceRequired();
        if(m instanceof Ghast){m.getAttribute(Attributes.FLYING_SPEED).setBaseValue(0);m.setNoGravity(true);}h.getLevel().addFreshEntity(m);return m;}
    static SkeletonBehaviorTests.PlayerFixture player(GameTestHelper h){var f=RaidBehaviorTests.player(h);f.player().setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.CARVED_PUMPKIN));return f;}
    static void proof(String s,Mob m,String detail){var r=RemainingState.runtime(m);BuildupMobTweaks.LOGGER.info("R4D_EVIDENCE scenario={} uuid={} ticks={} shots={} bindings={} releases={} hides={} help_blocks={} particles={} combos={} teleports={} attacks={} bursts={} arrows={} {}",s,m.getUUID(),m.tickCount,r.shots,r.bindings,r.releases,r.hides,r.helpBlocks,r.particles,r.combos,r.teleports,r.attacks,r.bursts,r.arrows,detail);}
    static void clean(Mob m){m.discard();for(var b:java.util.List.copyOf(RemainingState.runtime(m).balls))b.discard();}
    static void ghast(GameTestHelper h,boolean off){var m=mob(h,EntityTypes.GHAST);var f=player(h);if(off)m.addTag("buildupmobtweaks:vanilla_ai");
        Set<UUID> seen=new HashSet<>();List<Long> times=new ArrayList<>();List<Double> powers=new ArrayList<>();boolean[] charging={false};
        h.onEachTick(()->{if(m.getAttachedOrCreate(RemainingState.CHARGE)>10)charging[0]=true;for(var b:h.getLevel().getEntitiesOfClass(LargeFireball.class,m.getBoundingBox().inflate(48),b->b.getOwner()==m))if(seen.add(b.getUUID())){times.add(h.getLevel().getGameTime());powers.add(b.accelerationPower);}});
        h.runAtTickTime(260,()->{proof(off?"G01_vanilla_fallback":"G01_default",m,"times="+times+" power="+powers+" telegraph="+charging[0]+" playerHealth="+f.player().getHealth());
            h.assertTrue(m.getTarget()==f.player()&&times.size()>=2,"Native player acquisition and two actual large fireballs");for(int i=1;i<times.size();i++)h.assertTrue(times.get(i)-times.get(i-1)>=(off?60:140),"Actual native firing respects budget");
            h.assertTrue(powers.stream().allMatch(p->Math.abs(p-(off?.1:.06))<.00001)&&charging[0]!=off,"Independent speed/charge fallback");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=285)
    public void ghastNativeFireballsAndSavedBudget(GameTestHelper h){ghast(h,false);}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=285)
    public void ghastAllOffRestoresOriginalNativeCadence(GameTestHelper h){ghast(h,true);}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=215)
    public void ghastCreativeExitAndIndependentTelegraphOff(GameTestHelper h){var m=mob(h,EntityTypes.GHAST);var f=player(h);boolean[] phase={false};
        h.onEachTick(()->{if(!phase[0]&&m.isCharging()){phase[0]=true;f.player().setGameMode(GameType.CREATIVE);}});
        h.runAtTickTime(90,()->{h.assertTrue(phase[0]&&m.getTarget()==null&&!m.isCharging()&&m.getAttachedOrCreate(RemainingState.CHARGE)==0,"Real creative switch clears charge/target");f.player().setGameMode(GameType.SURVIVAL);m.addTag("buildupmobtweaks:disable_ghast_telegraph");});
        h.runAtTickTime(195,()->{h.assertTrue(RemainingState.runtime(m).shots>0&&m.getAttachedOrCreate(RemainingState.CHARGE)==0,"Native shots remain with only telegraph disabled");proof("G01_creative_and_visual_gate",m,"reacquired=true");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=190)
    public void ghastNativeReloadRetainsRealCooldown(GameTestHelper h){Ghast[] ref={mob(h,EntityTypes.GHAST)};var f=player(h);boolean[] reloaded={false};long[] ready={0};int[] lateShots={0};
        h.onEachTick(()->{var m=ref[0];if(!reloaded[0]&&RemainingState.runtime(m).shots==1){ready[0]=m.getAttached(RemainingState.DATA).getLongOr("ghast_ready",0);ref[0]=CombatTestWorld.reload(h,m);reloaded[0]=true;}
            if(reloaded[0]&&h.getLevel().getGameTime()<ready[0])lateShots[0]=Math.max(lateShots[0],RemainingState.runtime(ref[0]).shots);});
        h.runAtTickTime(170,()->{h.assertTrue(reloaded[0]&&lateShots[0]==0&&ref[0].getAttached(RemainingState.DATA).getLongOr("ghast_ready",0)>=ready[0],"Actual full entity save/load does not reset shooting budget");proof("G01_reload",ref[0],"ready="+ready[0]+" premature="+lateShots[0]);clean(ref[0]);f.close();h.succeed();});}
    static void blaze(GameTestHelper h,boolean off){blaze(h,off,false);}
    static void blaze(GameTestHelper h,boolean off,boolean all){var m=mob(h,EntityTypes.BLAZE);m.setNoGravity(true);m.getAttribute(Attributes.MOVEMENT_SPEED).setBaseValue(0);var f=player(h);if(off)m.addTag(all?"buildupmobtweaks:vanilla_ai":"buildupmobtweaks:disable_blaze_orbit");
        Set<UUID> projectiles=new HashSet<>();int[] peak={0};boolean[] moving={false};Map<UUID,net.minecraft.world.phys.Vec3> positions=new HashMap<>();
        h.onEachTick(()->{peak[0]=Math.max(peak[0],m.getPassengers().size());for(var b:h.getLevel().getEntitiesOfClass(SmallFireball.class,m.getBoundingBox().inflate(40),b->b.getOwner()==m)){
            projectiles.add(b.getUUID());if(b.getVehicle()==m){var previous=positions.put(b.getUUID(),b.position());if(previous!=null&&previous.distanceTo(b.position())>.001)moving[0]=true;}}});
        h.runAtTickTime(160,()->{proof(all?"B01_all_off":off?"B01_native_fallback":"B01_real_volley",m,"actual_ids="+projectiles.size()+" peak="+peak[0]+" orbit_moved="+moving[0]+" playerHealth="+f.player().getHealth());
            h.assertTrue(projectiles.size()==3,"Default normal difficulty native Goal creates exactly three projectiles in first volley");h.assertTrue(off?peak[0]==0&&RemainingState.runtime(m).bindings==0:peak[0]==3&&moving[0]&&RemainingState.runtime(m).releases==3,"Real orbit and bounded release, original non-orbit fallback");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=185)
    public void blazeActualNativeThreeBallOrbitAndRelease(GameTestHelper h){blaze(h,false);}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=185)
    public void blazeIndependentOrbitOffUsesNativeProjectileFlight(GameTestHelper h){blaze(h,true);}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=195)
    public void blazeStrafesDuringActualCharge(GameTestHelper h){var m=mob(h,EntityTypes.BLAZE);m.setNoGravity(true);var f=player(h);var origin=m.position();double[] moved={0};
        h.onEachTick(()->moved[0]=Math.max(moved[0],m.position().distanceTo(origin)));
        h.runAtTickTime(175,()->{proof("B01_strafe_probe",m,"max_motion="+moved[0]+" pos="+m.position()+" target="+m.getTarget()+" player="+f.player().position());h.assertTrue(moved[0]>.5&&RemainingState.runtime(m).bindings>0,"Actual charge strafing and native creation");proof("B01_strafe",m,"max_motion="+moved[0]);clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=185)
    public void blazeCreativeStopsActualOrbitAndNativeGoal(GameTestHelper h){var m=mob(h,EntityTypes.BLAZE);m.setNoGravity(true);var f=player(h);boolean[] bound={false};
        h.onEachTick(()->{if(!bound[0]&&!m.getPassengers().isEmpty()){bound[0]=true;f.player().setGameMode(GameType.CREATIVE);}});
        h.runAtTickTime(160,()->{h.assertTrue(bound[0]&&m.getTarget()==null&&m.getPassengers().isEmpty()&&RemainingState.runtime(m).balls.isEmpty(),"Real creative target exit removes owned balls");proof("B01_creative_exit",m,"balls=0");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=210)
    public void blazeActualDisableDoesNotTouchForeignPassengerOrShield(GameTestHelper h){var m=mob(h,EntityTypes.BLAZE);m.setNoGravity(true);var f=player(h);m.setItemSlot(EquipmentSlot.OFFHAND,new ItemStack(Items.SHIELD));var foreign=EntityTypes.ARMOR_STAND.create(h.getLevel(),EntitySpawnReason.COMMAND);h.getLevel().addFreshEntity(foreign);foreign.startRiding(m,true,false);boolean[] done={false};
        h.onEachTick(()->{if(!done[0]&&RemainingState.runtime(m).bindings>0){done[0]=true;m.addTag("buildupmobtweaks:disable_blaze_orbit");}});
        h.runAtTickTime(185,()->{h.assertTrue(done[0]&&foreign.getVehicle()==m&&m.getOffhandItem().is(Items.SHIELD)&&RemainingState.runtime(m).balls.isEmpty(),"Disable cleans only owned projectiles, preserves equipment/foreign passenger");proof("B01_disable_owned",m,"foreign=true shield=true");foreign.discard();clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=215)
    public void blazeActualPassengerReloadDiscardsOldBoundProjectile(GameTestHelper h){Blaze[] ref={mob(h,EntityTypes.BLAZE)};ref[0].setNoGravity(true);ref[0].getAttribute(Attributes.MOVEMENT_SPEED).setBaseValue(0);var f=player(h);boolean[] loaded={false};int[] oldCount={-1};UUID[] oldId={null};
        h.onEachTick(()->{if(!loaded[0]&&!ref[0].getPassengers().isEmpty()){oldId[0]=ref[0].getFirstPassenger().getUUID();ref[0]=CombatTestWorld.reloadPassengers(h,ref[0]);loaded[0]=true;oldCount[0]=ref[0].getPassengers().size();}});
        h.runAtTickTime(195,()->{h.assertTrue(loaded[0]&&ref[0].getPassengers().stream().noneMatch(e->e.getUUID().equals(oldId[0]))&&h.getLevel().getEntity(oldId[0])==null&&RemainingState.runtime(ref[0]).bindings<=3,"Native recursive load removes old in-flight phase and no duplicate volley");proof("B01_reload",ref[0],"immediate_loaded_passengers="+oldCount[0]+" old_uuid_absent=true");clean(ref[0]);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=165)
    public void blazeDeathCleansOwnedProjectilesWithoutFireChargeLoot(GameTestHelper h){var m=mob(h,EntityTypes.BLAZE);m.setNoGravity(true);var f=player(h);boolean[] died={false};
        h.onEachTick(()->{if(!died[0]&&!m.getPassengers().isEmpty()){died[0]=true;m.hurtServer(h.getLevel(),m.damageSources().generic(),1000);}});
        h.runAtTickTime(140,()->{h.assertTrue(died[0]&&!m.isAlive()&&RemainingState.runtime(m).balls.isEmpty(),"Native death cleans real balls");h.assertTrue(h.getLevel().getEntitiesOfClass(ItemEntity.class,m.getBoundingBox().inflate(8),i->i.getItem().is(Items.FIRE_CHARGE)).isEmpty(),"No upstream generated fire-charge reward");proof("B01_death",m,"extra_fire_charge=0");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=315)
    public void silverfishActualJumpConcealAndWorldCooldown(GameTestHelper h){var m=mob(h,EntityTypes.SILVERFISH);var f=player(h);double y=m.getY();double[] height={0};boolean[] invisible={false};
        h.runAtTickTime(10,()->m.hurtServer(h.getLevel(),m.damageSources().mobAttack(f.player()),1));h.onEachTick(()->{height[0]=Math.max(height[0],m.getY()-y);invisible[0]|=m.isInvisible();});
        h.runAtTickTime(290,()->{proof("F01_hide_probe",m,"height="+height[0]+" invisible_seen="+invisible[0]+" invisible="+m.isInvisible()+" sprinting="+m.isSprinting()+" alive="+m.isAlive()+" pos="+m.position());h.assertTrue(RemainingState.runtime(m).hides==1&&height[0]>.2&&invisible[0]&&!m.isInvisible()&&!m.isSprinting(),"Actual native scheduler jump/land/conceal ends and does not loop");proof("F01_hide",m,"height="+height[0]+" invisible_seen="+invisible[0]);clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=150)
    public void silverfishHiddenStillTakesDamageAndDisableRestores(GameTestHelper h){var m=mob(h,EntityTypes.SILVERFISH);var f=player(h);boolean[] hit={false};float[] damage={0};
        h.runAtTickTime(10,()->m.hurtServer(h.getLevel(),m.damageSources().mobAttack(f.player()),1));h.onEachTick(()->{if(!hit[0]&&m.isInvisible()){hit[0]=true;float old=m.getHealth();m.hurtServer(h.getLevel(),m.damageSources().generic(),1);damage[0]=old-m.getHealth();m.addTag("buildupmobtweaks:disable_silverfish_burrow");}});
        h.runAtTickTime(125,()->{h.assertTrue(hit[0]&&damage[0]>0&&!m.isInvisible()&&!m.isSprinting(),"No copied blanket invulnerability, disable restores active phase");proof("F01_damage_disable",m,"actual_damage="+damage[0]);clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=155)
    public void silverfishActualSaveLoadClearsOwnedInvisibility(GameTestHelper h){Silverfish[] ref={mob(h,EntityTypes.SILVERFISH)};var f=player(h);boolean[] loaded={false};long[] ready={0};
        h.runAtTickTime(10,()->ref[0].hurtServer(h.getLevel(),ref[0].damageSources().mobAttack(f.player()),1));h.onEachTick(()->{if(!loaded[0]&&ref[0].isInvisible()){ready[0]=ref[0].getAttached(RemainingState.DATA).getLongOr("hide_ready",0);ref[0]=CombatTestWorld.reload(h,ref[0]);loaded[0]=true;}});
        h.runAtTickTime(130,()->{h.assertTrue(loaded[0]&&!ref[0].isInvisible()&&!ref[0].isSprinting()&&ref[0].getAttached(RemainingState.DATA).getLongOr("hide_ready",0)==ready[0],"Real load restores phase while retaining reserved cooldown");proof("F01_reload",ref[0],"ready="+ready[0]);clean(ref[0]);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=115)
    public void silverfishShovelRealDamageAndIndependentOff(GameTestHelper h){var a=mob(h,EntityTypes.SILVERFISH);var b=mob(h,EntityTypes.SILVERFISH);b.snapTo(a.position().add(6,0,0),0,0);a.setNoAi(true);b.setNoAi(true);b.addTag("buildupmobtweaks:disable_silverfish_shovel_weakness");var f=player(h);f.player().setItemSlot(EquipmentSlot.MAINHAND,new ItemStack(Items.IRON_SHOVEL));
        h.runAtTickTime(30,()->{a.hurtServer(h.getLevel(),a.damageSources().mobAttack(f.player()),1);b.hurtServer(h.getLevel(),b.damageSources().mobAttack(f.player()),1);});
        h.runAtTickTime(45,()->{h.assertTrue(a.getHealth()==6&&b.getHealth()==7,"Actual direct shovel hit doubles damage only when enabled");proof("F02_shovel",a,"enabled_health="+a.getHealth()+" disabled_health="+b.getHealth());clean(a);clean(b);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d_help",structure=ARENA,maxTicks=345)
    public void silverfishRealHelpDeferredUntilEscapeEnds(GameTestHelper h){var rules=h.getLevel().getGameRules();boolean oldDrops=rules.get(net.minecraft.world.level.gamerules.GameRules.BLOCK_DROPS),oldGrief=rules.get(net.minecraft.world.level.gamerules.GameRules.MOB_GRIEFING);rules.set(net.minecraft.world.level.gamerules.GameRules.BLOCK_DROPS,true,h.getLevel().getServer());rules.set(net.minecraft.world.level.gamerules.GameRules.MOB_GRIEFING,true,h.getLevel().getServer());var m=mob(h,EntityTypes.SILVERFISH);m.getAttribute(Attributes.MOVEMENT_SPEED).setBaseValue(0);var f=player(h);h.setBlock(new BlockPos(9,2,8),Blocks.INFESTED_STONE);m.getAttribute(Attributes.KNOCKBACK_RESISTANCE).setBaseValue(1);boolean[] concealed={false},released={false},allySeen={false};Set<UUID> allyIds=new HashSet<>();
        h.runAtTickTime(10,()->m.hurtServer(h.getLevel(),m.damageSources().mobAttack(f.player()),1));h.onEachTick(()->{if(m.isInvisible()){concealed[0]=true;h.assertTrue(h.getBlockState(new BlockPos(9,2,8)).is(Blocks.INFESTED_STONE),"Native help must remain deferred throughout observed conceal");}if(RemainingState.runtime(m).helpBlocks>0)released[0]=true;for(var s:h.getLevel().getEntitiesOfClass(Silverfish.class,m.getBoundingBox().inflate(30)))if(s!=m){allySeen[0]=true;allyIds.add(s.getUUID());}});

        h.runAtTickTime(320,()->{var r=RemainingState.runtime(m);proof("F02_help_probe",m,"actual_ally_ids="+allyIds+" pos="+m.position());h.assertTrue(concealed[0]&&released[0]&&r.helpBlocks==1&&r.particles==1&&r.paused,"Native Goal really destroys infested block after escape and sends one bounded particle");h.assertTrue(allySeen[0]&&allyIds.size()==1,"Exactly one actually observed native spawned ally; ongoing combat may move it away");proof("F02_native_help",m,"actual_ally=true ids="+allyIds);for(var id:allyIds){var s=h.getLevel().getEntity(id);if(s!=null)s.discard();}m.discard();f.close();rules.set(net.minecraft.world.level.gamerules.GameRules.BLOCK_DROPS,oldDrops,h.getLevel().getServer());rules.set(net.minecraft.world.level.gamerules.GameRules.MOB_GRIEFING,oldGrief,h.getLevel().getServer());h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d_help_off",structure=ARENA,maxTicks=155)
    public void silverfishHideOffAndParticleOffRetainOriginalHelp(GameTestHelper h){var rules=h.getLevel().getGameRules();boolean oldDrops=rules.get(net.minecraft.world.level.gamerules.GameRules.BLOCK_DROPS),oldGrief=rules.get(net.minecraft.world.level.gamerules.GameRules.MOB_GRIEFING);rules.set(net.minecraft.world.level.gamerules.GameRules.BLOCK_DROPS,true,h.getLevel().getServer());rules.set(net.minecraft.world.level.gamerules.GameRules.MOB_GRIEFING,true,h.getLevel().getServer());var m=mob(h,EntityTypes.SILVERFISH);m.getAttribute(Attributes.MOVEMENT_SPEED).setBaseValue(0);m.addTag("buildupmobtweaks:disable_silverfish_burrow");m.addTag("buildupmobtweaks:disable_silverfish_call_particles");var f=player(h);h.setBlock(new BlockPos(9,2,8),Blocks.INFESTED_STONE);
        h.runAtTickTime(10,()->m.hurtServer(h.getLevel(),m.damageSources().mobAttack(f.player()),1));h.runAtTickTime(125,()->{var r=RemainingState.runtime(m);proof("F02_fallback_probe",m,"block="+h.getBlockState(new BlockPos(9,2,8)));h.assertTrue(r.hides==0&&r.helpBlocks==1&&r.particles==0,"Independent hide/particle disabled keeps real original wake-up");proof("F02_native_fallback",m,"hide=0 particles=0");for(var s:h.getLevel().getEntitiesOfClass(Silverfish.class,m.getBoundingBox().inflate(12)))s.discard();f.close();rules.set(net.minecraft.world.level.gamerules.GameRules.BLOCK_DROPS,oldDrops,h.getLevel().getServer());rules.set(net.minecraft.world.level.gamerules.GameRules.MOB_GRIEFING,oldGrief,h.getLevel().getServer());h.succeed();});}
    static Enderman enderman(GameTestHelper h){var m=mob(h,EntityTypes.ENDERMAN);m.getAttached(RemainingState.DATA).putString("birth","combo");return m;}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=245)
    public void endermanRetaliatesAndNativeTeleportComboReallyHits(GameTestHelper h){var m=enderman(h);var f=player(h);h.runAtTickTime(10,()->m.hurtServer(h.getLevel(),m.damageSources().mobAttack(f.player()),1));
        h.runAtTickTime(220,()->{var r=RemainingState.runtime(m);proof("N01_actual_combo",m,"playerHealth="+f.player().getHealth()+" ready="+m.getAttached(RemainingState.DATA).getLongOr("combo_ready",0));h.assertTrue(r.combos==1&&r.teleports==3&&r.attacks==3,"Real retaliation, three native successful teleports and three native melee damage events");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=235)
    public void endermanComboOffKeepsOrdinaryNativeMelee(GameTestHelper h){var m=enderman(h);m.addTag("buildupmobtweaks:disable_enderman_combo");var f=player(h);h.runAtTickTime(10,()->m.hurtServer(h.getLevel(),m.damageSources().mobAttack(f.player()),1));
        h.runAtTickTime(210,()->{h.assertTrue(RemainingState.runtime(m).combos==0&&f.player().getHealth()<1000,"Independent combo off keeps actual native melee");proof("N01_native_fallback",m,"health="+f.player().getHealth());clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=235)
    public void endermanSpectatorExitCancelsRealCombo(GameTestHelper h){var m=enderman(h);var f=player(h);boolean[] changed={false};h.runAtTickTime(10,()->m.hurtServer(h.getLevel(),m.damageSources().mobAttack(f.player()),1));
        h.onEachTick(()->{if(!changed[0]&&RemainingState.runtime(m).teleports>0){changed[0]=true;f.player().setGameMode(GameType.SPECTATOR);}});
        h.runAtTickTime(210,()->{var r=RemainingState.runtime(m);h.assertTrue(changed[0]&&m.getTarget()==null&&r.target==null&&r.teleports==1,"Real spectator switch cancels later attempts and target");proof("N01_spectator_exit",m,"no_remaining_attempts=true");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=245)
    public void endermanRealReloadReservesBudgetAndLeavesCarriedBlock(GameTestHelper h){Enderman[] ref={enderman(h)};ref[0].setCarriedBlock(Blocks.GRASS_BLOCK.defaultBlockState());var f=player(h);boolean[] loaded={false};long[] ready={0};h.runAtTickTime(10,()->ref[0].hurtServer(h.getLevel(),ref[0].damageSources().mobAttack(f.player()),1));
        h.onEachTick(()->{if(!loaded[0]&&RemainingState.runtime(ref[0]).teleports>0){ready[0]=ref[0].getAttached(RemainingState.DATA).getLongOr("combo_ready",0);ref[0]=CombatTestWorld.reload(h,ref[0]);loaded[0]=true;}});
        h.runAtTickTime(220,()->{h.assertTrue(loaded[0]&&ref[0].getAttached(RemainingState.DATA).getLongOr("combo_ready",0)==ready[0]&&RemainingState.runtime(ref[0]).combos==0&&ref[0].getCarriedBlock()!=null,"Actual loaded entity retains cooldown/birth/carried block, no in-flight combo restoration");proof("N01_reload",ref[0],"ready="+ready[0]);clean(ref[0]);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=90)
    public void endermanSpeedModifierIsTransientAndIndependentlyRemoved(GameTestHelper h){var m=mob(h,EntityTypes.ENDERMAN);double base=m.getAttribute(Attributes.MOVEMENT_SPEED).getBaseValue();double[] active={0};
        h.runAtTickTime(20,()->{active[0]=m.getAttributeValue(Attributes.MOVEMENT_SPEED);h.assertTrue(Math.abs(active[0]-base*.85)<.00001,"Real server tick applies own transient speed modifier");m.addTag("buildupmobtweaks:disable_enderman_speed");});
        h.runAtTickTime(60,()->{h.assertTrue(m.getAttribute(Attributes.MOVEMENT_SPEED).getBaseValue()==base&&m.getAttributeValue(Attributes.MOVEMENT_SPEED)==base,"Disable removes own modifier and preserves base");proof("N01_speed",m,"base="+base+" active="+active[0]);clean(m);h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=65)
    public void endermanDefaultActualBirthSampleAndNoReroll(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);int chosen=0;for(int i=0;i<1000;i++){var m=EntityTypes.ENDERMAN.create(h.getLevel(),EntitySpawnReason.NATURAL);m.snapTo(h.absolutePos(new BlockPos(8,2,8)),0,0);m.getRandom().setSeed(381000L+i);m.finalizeSpawn(h.getLevel(),h.getLevel().getCurrentDifficultyAt(m.blockPosition()),EntitySpawnReason.NATURAL,null);if(m.getAttached(RemainingState.DATA).getStringOr("birth","").equals("combo"))chosen++;m.discard();}
        h.assertTrue(chosen>=30&&chosen<=110,"Default 70/1000 native finalizeSpawn sample, not natural spawner evidence");BuildupMobTweaks.LOGGER.info("R4D_EVIDENCE scenario=N01_default_birth n=1000 combo={} native_finalizeSpawn=true natural_spawner=NOT_RUN",chosen);var m=enderman(h);var uuid=m.getUUID();var loaded=CombatTestWorld.reload(h,m);h.assertTrue(loaded.getUUID().equals(uuid)&&loaded.getAttached(RemainingState.DATA).getStringOr("birth","").equals("combo"),"No reroll at actual load");clean(loaded);h.succeed();}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=90)
    public void unknownDataPreservesNativeGoalsAndPayload(GameTestHelper h){SkeletonBehaviorTests.floor(h,false);var m=EntityTypes.ENDERMAN.create(h.getLevel(),EntitySpawnReason.COMMAND);m.snapTo(h.absolutePos(new BlockPos(8,2,8)),0,0);var d=new net.minecraft.nbt.CompoundTag();d.putInt("version",99);d.putString("birth","future");m.setAttached(RemainingState.DATA,d);h.getLevel().addFreshEntity(m);var before=d.copy();
        h.runAtTickTime(60,()->{h.assertTrue(m.getAttached(RemainingState.DATA).equals(before)&&!RemainingState.runtime(m).installed,"Unknown data untouched; no custom Goals installed");proof("future_data",m,"version=99 untouched=true");clean(m);h.succeed();});}
    static void creeper(GameTestHelper h,boolean off){var m=mob(h,EntityTypes.CREEPER);if(off)m.addTag("buildupmobtweaks:disable_creeper_embedded_arrows");m.setArrowCount(3);m.ignite();Set<UUID> arrows=new HashSet<>();boolean[] noPickup={true};
        h.onEachTick(()->{for(var a:h.getLevel().getEntitiesOfClass(AbstractArrow.class,m.getBoundingBox().inflate(40))){arrows.add(a.getUUID());noPickup[0]&=a.pickup==AbstractArrow.Pickup.DISALLOWED;}});
        h.runAtTickTime(60,()->{h.assertTrue(m.isRemoved()&&arrows.size()==(off?0:3)&&noPickup[0],"Actual native fuse explosion, only embedded count and no ammunition duplication");proof(off?"C01_arrows_off":"C01_native_explosion",m,"actual_arrows="+arrows.size());clean(m);h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=90)
    public void creeperRealExplosionReleasesUnpickableEmbeddedArrows(GameTestHelper h){creeper(h,false);}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=90)
    public void creeperIndependentArrowOffKeepsNativeExplosion(GameTestHelper h){creeper(h,true);}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=255)
    public void spiderNativePestTargetAndGateExit(GameTestHelper h){var m=mob(h,EntityTypes.SPIDER);var pest=mob(h,EntityTypes.SILVERFISH);pest.snapTo(m.position().add(0,0,4),0,0);pest.setNoAi(true);pest.getAttribute(Attributes.MAX_HEALTH).setBaseValue(1000);pest.setHealth(1000);boolean[] targeted={false};
        h.onEachTick(()->targeted[0]|=m.getTarget()==pest);h.runAtTickTime(150,()->{h.assertTrue(targeted[0]&&pest.getHealth()<1000,"Native target Goal acquires pest and SpiderAttackGoal actually damages it");m.addTag("buildupmobtweaks:disable_spider_hunts_pests");});
        h.runAtTickTime(225,()->{h.assertTrue(m.getTarget()!=pest,"Active added target Goal yields on independent disable");proof("S07_native_hunt",m,"pestHealth="+pest.getHealth());clean(m);clean(pest);h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d_hard",structure=ARENA,maxTicks=825)
    public void breezeActualHardNativeBrainJumpAndLandBurst(GameTestHelper h){var server=h.getLevel().getServer();var previous=h.getLevel().getDifficulty();server.setDifficulty(net.minecraft.world.Difficulty.HARD,true);var m=mob(h,EntityTypes.BREEZE);var f=player(h);double y=m.getY();double[] height={0};boolean[] jumping={false};int[] nativeCharges={0};
        h.onEachTick(()->{height[0]=Math.max(height[0],m.getY()-y);jumping[0]|=m.getPose()==Pose.LONG_JUMPING;nativeCharges[0]=Math.max(nativeCharges[0],h.getLevel().getEntitiesOfClass(net.minecraft.world.entity.projectile.hurtingprojectile.windcharge.BreezeWindCharge.class,m.getBoundingBox().inflate(45)).size());});
        h.runAtTickTime(800,()->{proof("BR01_native_hard",m,"jump="+jumping[0]+" height="+height[0]+" native_charges="+nativeCharges[0]+" takeoff_ready="+m.getAttached(RemainingState.DATA).getLongOr("takeoff_ready",0)+" landing_ready="+m.getAttached(RemainingState.DATA).getLongOr("landing_ready",0));h.assertTrue(jumping[0]&&height[0]>.5&&RemainingState.runtime(m).bursts>=2,"Actual native Brain long jump and landing produce bounded bursts");clean(m);f.close();server.setDifficulty(previous,true);h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=275)
    public void ghastRealWallInterruptsChargeAndNativeLosReacquires(GameTestHelper h){var m=mob(h,EntityTypes.GHAST);var f=player(h);boolean[] blocked={false};h.onEachTick(()->{if(!blocked[0]&&m.getAttachedOrCreate(RemainingState.CHARGE)>=10){blocked[0]=true;for(int x=4;x<=14;x++)for(int y=2;y<=9;y++)h.setBlock(new BlockPos(x,y,12),Blocks.STONE);}});
        h.runAtTickTime(90,()->{h.assertTrue(blocked[0]&&RemainingState.runtime(m).shots==0&&!m.isCharging(),"Actual LOS obstruction prevents firing and drains native charge");for(int x=4;x<=14;x++)for(int y=2;y<=9;y++)h.setBlock(new BlockPos(x,y,12),Blocks.AIR);});
        h.runAtTickTime(250,()->{h.assertTrue(RemainingState.runtime(m).shots>0,"Removing wall restores native acquisition and real shooting");proof("G01_actual_los",m,"blocked_then_reacquired=true");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d_pause",structure=ARENA,maxTicks=160)
    public void silverfishPauseOffReallyWalksWhileOriginalHelpRuns(GameTestHelper h){var m=mob(h,EntityTypes.SILVERFISH);m.getAttribute(Attributes.MOVEMENT_SPEED).setBaseValue(.1);m.getAttribute(Attributes.KNOCKBACK_RESISTANCE).setBaseValue(1);m.addTag("buildupmobtweaks:disable_silverfish_burrow");m.addTag("buildupmobtweaks:disable_silverfish_call_pause");var f=player(h);h.setBlock(new BlockPos(9,2,8),Blocks.INFESTED_STONE);var rules=h.getLevel().getGameRules();boolean grief=rules.get(net.minecraft.world.level.gamerules.GameRules.MOB_GRIEFING);rules.set(net.minecraft.world.level.gamerules.GameRules.MOB_GRIEFING,true,h.getLevel().getServer());var origin=m.position();double[] moved={0};
        h.runAtTickTime(10,()->m.hurtServer(h.getLevel(),m.damageSources().mobAttack(f.player()),1));h.onEachTick(()->moved[0]=Math.max(moved[0],m.position().distanceTo(origin)));
        h.runAtTickTime(135,()->{var r=RemainingState.runtime(m);proof("F02_pause_off_probe",m,"motion="+moved[0]+" pos="+m.position()+" paused="+r.paused+" block="+h.getBlockState(new BlockPos(9,2,8)));h.assertTrue(r.helpBlocks==1&&!r.paused&&moved[0]>.5,"Independent pause off preserves actual walking and native help");proof("F02_pause_off",m,"motion="+moved[0]);for(var s:h.getLevel().getEntitiesOfClass(Silverfish.class,m.getBoundingBox().inflate(40)))s.discard();f.close();rules.set(net.minecraft.world.level.gamerules.GameRules.MOB_GRIEFING,grief,h.getLevel().getServer());h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d_breeze_off",structure=ARENA,maxTicks=650)
    public void breezeActualIndependentTakeoffOffAndGriefingFalse(GameTestHelper h){var server=h.getLevel().getServer();var previous=h.getLevel().getDifficulty();server.setDifficulty(net.minecraft.world.Difficulty.HARD,true);var rules=h.getLevel().getGameRules();boolean grief=rules.get(net.minecraft.world.level.gamerules.GameRules.MOB_GRIEFING);rules.set(net.minecraft.world.level.gamerules.GameRules.MOB_GRIEFING,false,server);
        var m=mob(h,EntityTypes.BREEZE);m.addTag("buildupmobtweaks:disable_breeze_takeoff_burst");var f=player(h);h.setBlock(new BlockPos(9,2,9),Blocks.LEVER);boolean[] nativeJump={false},disabled={false};
        h.onEachTick(()->{nativeJump[0]|=m.getPose()==Pose.LONG_JUMPING;if(!disabled[0]&&RemainingState.runtime(m).bursts>0){disabled[0]=true;m.addTag("buildupmobtweaks:disable_breeze_landing_burst");}});
        h.runAtTickTime(620,()->{proof("BR01_independent_off",m,"jump="+nativeJump[0]+" lever="+h.getBlockState(new BlockPos(9,2,9))+" takeoff_ready="+m.getAttached(RemainingState.DATA).getLongOr("takeoff_ready",0));h.assertTrue(nativeJump[0]&&disabled[0]&&RemainingState.runtime(m).bursts==1&&m.getAttached(RemainingState.DATA).getLongOr("takeoff_ready",0)==0,"Actual Brain jumps, only enabled landing burst once, live disable holds");h.assertTrue(!h.getBlockState(new BlockPos(9,2,9)).getValue(net.minecraft.world.level.block.LeverBlock.POWERED),"Griefing false preserves nearby real lever");clean(m);f.close();rules.set(net.minecraft.world.level.gamerules.GameRules.MOB_GRIEFING,grief,server);server.setDifficulty(previous,true);h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=645)
    public void breezeNormalNativeJumpHasNoExtraBurst(GameTestHelper h){var m=mob(h,EntityTypes.BREEZE);var f=player(h);boolean[] jump={false};h.onEachTick(()->jump[0]|=m.getPose()==Pose.LONG_JUMPING);
        h.runAtTickTime(620,()->{h.assertTrue(h.getLevel().getDifficulty()==net.minecraft.world.Difficulty.NORMAL&&jump[0]&&RemainingState.runtime(m).bursts==0,"Original normal Brain jump, no hard-only burst");proof("BR01_normal",m,"actual_jump=true bursts=0");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=205)
    public void creeperActualNativeSwellRetreatsAfterHit(GameTestHelper h){var m=mob(h,EntityTypes.CREEPER);var f=player(h);f.player().snapTo(m.position().add(0,0,2.6),0,0);boolean[] damaged={false},retreated={false};float[] start={0};
        h.onEachTick(()->{if(!damaged[0]&&m.getSwelling(1)>.15){damaged[0]=true;start[0]=m.getSwelling(1);m.hurtServer(h.getLevel(),m.damageSources().mobAttack(f.player()),1);}if(damaged[0]&&m.getSwelling(1)<start[0]&&m.getSwellDir()<0)retreated[0]=true;});
        h.runAtTickTime(175,()->{h.assertTrue(damaged[0]&&retreated[0],"Actual survival acquisition and original SwellGoal backs fuse after real hit");proof("C01_actual_hit_delay",m,"native_fuse_retreat=true");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=265)
    public void ghastNoAiClearsActiveChargeAndResumesNativeWindup(GameTestHelper h){var m=mob(h,EntityTypes.GHAST);var f=player(h);boolean[] paused={false};h.onEachTick(()->{if(!paused[0]&&m.getAttachedOrCreate(RemainingState.CHARGE)>=10){paused[0]=true;m.setNoAi(true);}});
        h.runAtTickTime(100,()->{h.assertTrue(paused[0]&&m.getAttachedOrCreate(RemainingState.CHARGE)==0&&!m.isCharging()&&RemainingState.runtime(m).shots==0,"Actual NoAI ticks clear held charge without a shot");m.setNoAi(false);});
        h.runAtTickTime(125,()->h.assertTrue(RemainingState.runtime(m).shots==0,"Resume requires full native windup"));h.runAtTickTime(240,()->{h.assertTrue(RemainingState.runtime(m).shots>0,"Actual native firing resumes after NoAI");proof("G01_no_ai",m,"clean_resume=true");clean(m);f.close();h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d_config",structure=ARENA,maxTicks=665)
    public void endermanConfiguredCooldownDelaysActualSecondCombo(GameTestHelper h){var field=BuildupMobTweaks.config().hostile.extended.special_cooldown;int old=field.get();field.accept(800);var m=enderman(h);var f=player(h);h.runAtTickTime(10,()->m.hurtServer(h.getLevel(),m.damageSources().mobAttack(f.player()),1));
        h.runAtTickTime(640,()->{var r=RemainingState.runtime(m);h.assertTrue(r.combos==1&&r.teleports==3&&r.attacks==3&&m.getAttached(RemainingState.DATA).getLongOr("combo_ready",0)-r.start==800,"Configured 800 tick budget prevents actual second combo beyond the default 400 deadline");proof("N01_configured_budget",m,"budget=800 combos=1");clean(m);f.close();field.accept(old);h.succeed();});}
    @GameTest(environment="buildupmobtweaks:r4d",structure=ARENA,maxTicks=185)
    public void blazeAllOffRetainsActualOriginalVolleyWithoutOwnedPassengers(GameTestHelper h){blaze(h,true,true);}
}
